### ISSUE TITLE
Missing dependencies(diff_gaussian_rasterization)

### ISSUE THREAD

**Issue by ReaLifecyborg** [NIRVANALAN/GaussianAnything#3]
I tried installing the local setup on my host machine(windows 11 with powershell and conda) and also my wsl(ubuntu),i went into the error as following when running the i23d bash script(stage 1) with the command:
bash shell_scripts/release/inference/i23d/i23d-stage1.sh

heres the partial information and full error txt file:
Traceback (most recent call last):
  File "/home/username/gaussian/GaussianAnything/scripts/vit_triplane_sit_sample.py", line 23, in <module>
    from guided_diffusion.script_util import (
  File "/home/username/gaussian/GaussianAnything/./guided_diffusion/script_util.py", line 14, in <module>
    from dit.dit_trilatent import DiT_models as DiT_models_t23d
  File "/home/username/gaussian/GaussianAnything/./dit/dit_trilatent.py", line 15, in <module>
    from vit.vit_triplane import XYZPosEmbed
  File "/home/username/gaussian/GaussianAnything/./vit/vit_triplane.py", line 18, in <module>
    from nsr.networks_stylegan2 import Generator as StyleGAN2Backbone
  File "/home/username/gaussian/GaussianAnything/./nsr/__init__.py", line 2, in <module>
    from .train_util import TrainLoop3DRec, TrainLoop3DRecTrajVis
  File "/home/username/gaussian/GaussianAnything/./nsr/train_util.py", line 12, in <module>
    from nsr.gs import GaussianRenderer
  File "/home/username/gaussian/GaussianAnything/./nsr/gs.py", line 8, in <module>
    from diff_gaussian_rasterization import (
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

[gaerrormesg.txt](https://github.com/user-attachments/files/17970024/gaerrormesg.txt)
also theres some typo in the setup part on readme file:
pip intall -r requrements.txt
should be pip install -r requirements.txt
also when it is installing the requirements.txt without a torch prior to it,it would run into error as follow(can be resolved by first pip installing torch):
Collecting git+https://github.com/facebookresearch/pytorch3d.git@stable (from -r requirements.txt (line 48))
  Cloning https://github.com/facebookresearch/pytorch3d.git (to revision stable) to /tmp/pip-req-build-z2lmwm8q
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/pytorch3d.git /tmp/pip-req-build-z2lmwm8q
  Running command git checkout -q 75ebeeaea0908c5527e7b1e305fbc7681382db47
  Resolved https://github.com/facebookresearch/pytorch3d.git to commit 75ebeeaea0908c5527e7b1e305fbc7681382db47
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-z2lmwm8q/setup.py", line 15, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I googled a bit and found that the module of diff_gaussian_rasterization can be found at https://github.com/graphdeco-inria/gaussian-splatting as a submodule in that project, but so far i have no luck installing it that way with pip install submodules/diff_gaussian_rasterization after git clone with --recursive flag, i hope the information i provide is enough and im grateful for your time to read this.
my hardware spec is:
rtx4090(24g)+ryzen 9 7950x
if you need any extra information,please let me know

**Comment by NIRVANALAN** [comment]
Hi, thanks for letting me know the environment installation issue. I have fixed the script and feel free to update by ```git pull```.

Besides, I accidentally put the 3DGS dependency (```diff_gaussian_rasterization```) in my current repo, which is not used. This dependency is removed from the code in the latest commit, please feel free to try.

Keep me updated if there are any issues I can help with.

**Comment by ReaLifecyborg** [comment]
I tried again today and im able to make through the install process from the new readme file, however i encountered this error when running the bash script for i23d 1st stage:
 param_schemas = callee.param_schemas()
Traceback (most recent call last):
  File "/home/user/gaussian/GaussianAnything/scripts/vit_triplane_sit_sample.py", line 23, in <module>
    from guided_diffusion.script_util import (
  File "/home/user/gaussian/GaussianAnything/./guided_diffusion/script_util.py", line 6, in <module>
    from cldm.cldm import ControlledUnetModel, ControlNet
  File "/home/user/gaussian/GaussianAnything/./cldm/cldm.py", line 14, in <module>
    from ldm.modules.attention import SpatialTransformer
  File "/home/user/gaussian/GaussianAnything/./ldm/modules/attention.py", line 32, in <module>
    from torch.nn.attention import sdpa_kernel, SDPBackend
ModuleNotFoundError: No module named 'torch.nn.attention'
the full error log can be found here:
[gaerrormesg.txt](https://github.com/user-attachments/files/17979763/gaerrormesg.txt)
my environment are as follows:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
and
2.1.0+cu118 11.8
with all modules in requirements.txt installed and all install instruction script run with success

Again,thanks for your help and i really appreciate it!

**Comment by NIRVANALAN** [comment]
Hi, thanks for your message.

The lack of torch.nn.attention is perhaps due to torch==2.1.0 version issue. This module is introduced in torch==2.3.0 or so. I have removed the dependency in the latest commit and please feel free to update.

Note that in practice I adopted torch==2.3.0, but in the hugging face demo only <=2.2 or >=2.4 is allowed (seems that torch 2.3 has some bugs). To support the xformers version (especially fused_mlp), I have degraded the torch version to 2.1.0. If you have used torch 2.3.0 in your local machine and managed to run the code, it should be totally fine.

**Comment by ReaLifecyborg** [comment]
im still not able to run the script from freshly setting the environment as the readme process,at first its nvcc not installed in the environment,then its cub missing and version mismatch,also xformers in the requirements require pytorch2.3.0,im stuck with  pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable" by missing nvcc then after resolving the nvcc issue, im stuck with pip install "git+https://github.com/hbb1/diff-surfel-rasterization.git" with nvidia cub missing due to mismatch
i was trying to see if one of my previous research can adapt and improve on this project for normal recreation,my previous research is an improved version of normal map calculation that would take full image input and output a normal map calculated from the process,i have yet to publish the research, but heres some result for that:

![result_0](https://github.com/user-attachments/assets/962c48e9-a818-4c31-8c2f-d2c3af00f8c3)
from image
![image](https://github.com/user-attachments/assets/d3ecc668-007b-46fd-b1c4-b7df17db5566)
and
![result_0](https://github.com/user-attachments/assets/332daa93-8979-4428-b396-3eb9ef6de002)
from image
![i3](https://github.com/user-attachments/assets/528552a3-a30e-4848-a1fb-16f221b26f73)
as it surpass the previous sota solution from ic light:
![328715556-2daab276-fdfa-4b0c-abcb-e591f575598a](https://github.com/user-attachments/assets/df6b645e-4069-43ea-bf9d-0ade0fe2d8db)

**Comment by NIRVANALAN** [comment]
Very cool results! 

For pytorch3D issue, you can refer to the official instructions [here](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md), and first call ```conda install -c bottler nvidiacub``` to fix the cub installation issue.

I am very happy and honored to have you helping improving the mesh normal performance. Let's keep connected and please let me know if you have any issues.

Perhaps you can refer to my [gradio demo](https://huggingface.co/spaces/yslan/GaussianAnything-AIGC3D/blob/main/requirements.txt). The huggingface docker first calls "pip install requirements.txt", followed by "python app.py" to deploy the environment automatically. Let me know whether that helps.
